Develop
kerelape/gophermart pull request #1
Opened 2023-05-31 10:08 UTC by kerelape

2023-06-01 18:04 UTC, tmvrus requested changes
- не стоит злоупотреблять паникой
- стоит начать писать тесты

К работе только одно принципиальное замечание - обработка ErrTooManyRequests,
все остальные замечания рекомендуемые.

2023-06-01 18:04 UTC, tmvrus commented on internal/accrual/accrual.go
> +	out, outError := http.NewRequestWithContext(ctx, http.MethodGet, a.Address+"/api/orders/"+order, strings.NewReader(""))
Для запросов без тела можно передавать nil вместо Reader

2023-06-01 18:04 UTC, tmvrus commented on internal/accrual/accrual.go
> +			panic(fmt.Errorf("unknown response code %d", in.StatusCode))
бросать панку нужно примерно никогда, тем более что тут вполне можно вернуть ошибку

2023-06-01 18:04 UTC, tmvrus commented on internal/accrual/accrual.go
> +			return OrderInfo{}, ErrTooManyRequests
ErrTooManyRequests никак не обрабатывается вызывающим кодом, это требование должно быть реализовано

2023-06-01 18:04 UTC, tmvrus commented on internal/accrual/accrual.go
> +	var response struct {
эта структура копирует type OrderInfo struct, почему не добавить туда json-теги?

2023-06-01 18:04 UTC, tmvrus commented on internal/gophermart/api/rest/user/balance/balance.go
> +	}
зачем использовать any если Current и Withdrawn типизированы
```
type Balance struct {
	Current   float64
	Withdrawn float64
}
```

2023-06-01 18:04 UTC, tmvrus commented on internal/gophermart/api/rest/user/balance/balance.go
> +	}
это код повторяется в 5 местах проекта, почему бы не сделать из этого middleware или helper-функцию?

2023-06-01 18:04 UTC, tmvrus commented on internal/gophermart/api/rest/user/balance/balance.go
> +		panic(err)
тут ведь можно не бросать панику и вернуть ошибку пользователю

2023-06-01 18:04 UTC, tmvrus commented on internal/gophermart/idp/postgres_identity.go
> +	)
ничто не мешает трем разным запросам вычитать одинаковый баланс а затем снизить его до отрицательных значений

2023-06-01 18:04 UTC, tmvrus commented on internal/gophermart/idp/postgres_identity_database.go
> +	rows, findDuplicateError := p.conn.Query(ctx, `SELECT ALL FROM identities where username = $1`, username)
у pgx есть метод QueryRow для получения единственной записи

2023-06-01 18:04 UTC, tmvrus commented on internal/gophermart/idp/postgres_identity_database.go
> +	return transaction.Commit(ctx)
в этой транзакции нет никакого смысла потому что она содержит тольк один запрос

2023-06-03 18:09 UTC, kerelape commented on internal/accrual/accrual.go
> +			return OrderInfo{}, ErrTooManyRequests
Вижу такой варинт: вынести это в отдельную горутину и вызывать `time.Sleep(n)`, когда возникает эта ошибка. Это верно или я перемудриваю либо понимаю что то неправильно?

2023-06-04 22:22 UTC, kerelape commented on internal/gophermart/api/rest/user/balance/balance.go
> +	}
Как и trailing-comma - для лучших diff'ов в будущем. 

Эта `map` представляет JSON, и - гипотетически - однажды там может понадобиться отдавать, что-то еще другого типа, и придется менять тип мапы опять на `any`.

2023-06-04 23:05 UTC, tmvrus commented on internal/gophermart/api/rest/user/balance/balance.go
> +	}
https://ru.wikipedia.org/wiki/YAGNI

2023-06-04 23:06 UTC, tmvrus approved these changes

2023-06-05 08:49 UTC, merged